### ISSUE TITLE
Removing users w/ tasks and projects throws a ForeignKeyViolation

### ISSUE THREAD

**Issue by AnotherJulia** [AnotherJulia/Project-manager-cli#7]
`thread 'main' panicked at 'Error removing user: DatabaseError(ForeignKeyViolation, "update or delete on table "users" violates foreign key constraint "projects_user_name_fkey" on table "projects"")', src/operations/user.rs:112:14 stack backtrace: 0: rust_begin_unwind at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5 1: core::panicking::panic_fmt at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14 2: core::result::unwrap_failed at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/result.rs:1651:5 3: pit::operations::user::handle_user_command 4: pit::main note: Some details are omitted, run with RUST_BACKTRACE=full for a verbose backtrace.
`

**Source of problem**: the user we're trying to remove still has some tasks and projects in the other databases. By removing the user it violetes the foreign keys in those. 

**Todo**: 
- [ ] Ask for deletion confirmation
- [ ] if yes -> delete the tasks and project and then continue removing the user .
- [ ] if no -> abort
